kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-truenas-nfs-api
  namespace: democratic-csi
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi