cluster:
  name: homelab

global:
  scrapeInterval: "30s"

destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
    auth:
      type: basic
      usernameKey: gcloud_metrics_user
      passwordKey: gcloud_metrics_password
    secret:
      create: false
      name: grafana-k8s-monitoring
      namespace: monitoring
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    auth:
      type: basic
      usernameKey: gcloud_logs_user
      passwordKey: gcloud_logs_password
    secret:
      create: false
      name: grafana-k8s-monitoring
      namespace: monitoring
  - name: grafana-cloud-traces
    type: otlp
    url: https://tempo-eu-west-0.grafana.net:443
    protocol: grpc
    auth:
      type: basic
      usernameKey: gcloud_otlp_password
      passwordKey: gcloud_otlp_password
    secret:
      create: false
      name: grafana-k8s-monitoring
      namespace: monitoring
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true

clusterMetrics:
  enabled: true
  node-exporter:
    metricsTuning:
      useIntegrationAllowList: true
      includeMetrics:
        - node_hwmon_temp_celsius

annotationAutodiscovery:
  enabled: true

clusterEvents:
  enabled: true

nodeLogs:
  enabled: true
  journal:
    # The list of systemd units to keep scraped logs from. If empty, all units are scraped.
    units: []

podLogs:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  connectors:
    grafanaCloudMetrics:
      enabled: true

alloy-metrics:
  enabled: true
  logging:
    level: warn
  alloy:
    resources:
      requests:
        memory: "640Mi"
        cpu: "0.07"

alloy-singleton:
  enabled: true
  logging:
    level: warn
  alloy:
    resources:
      requests:
        memory: "64Mi"
        cpu: "0.01"

alloy-logs:
  enabled: true
  logging:
    level: warn
  alloy:
    resources:
      requests:
        memory: "210Mi"
        cpu: "0.07"

alloy-receiver:
  enabled: true
  logging:
    level: warn
  alloy:
    resources:
      requests:
        memory: "164Mi"
        cpu: "0.02"
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP

integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
            - alloy-receiver