apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-cert
spec:
  secretName: forgejo-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - git.kevingomez.fr
