apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: "Recreate"

  selector:
    matchLabels:
      app: forgejo

  template:
    metadata:
      labels:
        app: forgejo
    spec:
      automountServiceAccountToken: false

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values: [ssd]

      terminationGracePeriodSeconds: 30

      containers:
        - name: forgejo
          image: {{ .Values.forgejo.image }}:{{ .Values.forgejo.tag }}
          env:
            # Misc
            - name: FORGEJO_TEMP
              value: /tmp/forgejo
            - name: FORGEJO__log__LEVEL
              value: Warn # https://docs.gitea.com/administration/logging-config#the-log-section
            - name: FORGEJO__server__PUBLIC_URL_DETECTION
              value: auto
            - name: FORGEJO__server__SSH_DOMAIN
              value: git-ssh.kevingomez.fr

            # Metrics - https://docs.gitea.com/administration/config-cheat-sheet#metrics-metrics
            - name: FORGEJO__metrics__ENABLED
              value: 'true'
            - name: FORGEJO__metrics__ENABLED_ISSUE_BY_LABEL
              value: 'true'
            - name: FORGEJO__metrics__ENABLED_ISSUE_BY_REPOSITORY
              value: 'true'
            - name: FORGEJO__metrics__TOKEN
              valueFrom:
                secretKeyRef:
                  name: metrics-token
                  key: password

            # Database
            - name: FORGEJO__database__DB_TYPE
              value: postgres
            - name: FORGEJO__database__HOST
              value: postgres:5432
            - name: FORGEJO__database__NAME
              value: forgejo
            - name: FORGEJO__database__USER
              value: forgejo
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password

            # Mailer
            - name: FORGEJO__mailer__ENABLED
              value: "true"
            - name: FORGEJO__mailer__FROM
              value: noreply@git.kevingomez.fr
            - name: FORGEJO__mailer__PROTOCOL
              value: "smtp+starttls"
            - name: FORGEJO__mailer__SMTP_ADDR
              value: smtp.fastmail.com
            - name: FORGEJO__mailer__SMTP_PORT
              value: "587"
            - name: FORGEJO__mailer__USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: FORGEJO__mailer__PASSWD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
          resources:
            requests:
              memory: "264Mi"
              cpu: "20m"

          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 2222

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10

          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: data
              mountPath: /var/lib/gitea
            - name: config
              mountPath: /etc/gitea
            - name: temp
              mountPath: /tmp

      volumes:
        - name: data
          nfs:
            server: beet.lab
            path: /mnt/main/forgejo
        - name: config
          persistentVolumeClaim:
            claimName: forgejo-config
        - name: temp
          emptyDir: {}