apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`git.kevingomez.fr`)
      services:
        - kind: Service
          name: forgejo-http
          port: http
  tls:
    secretName: forgejo-cert