apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-cert
spec:
  secretName: prowlarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.kevingomez.fr
