apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 3

  # the PVC used by prowlarr is defined as ReadWriteOnce, so only one pod can
  # access it at any time
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: prowlarr

  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: TZ
              value: 'Europe/Stockholm'
          ports:
            - name: http
              containerPort: 9696
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
          resources:
            requests:
              memory: "200Mi"
              cpu: "20m"

      volumes:
        - name: prowlarr-config
          nfs:
            server: beet.lab
            path: /mnt/main/k8s/nfs/volumes/pvc-c191c6d9-70bc-4c6a-9e20-d2f039e71ed9