apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  labels:
    app: prowlarr
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi