apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    theme:
      background-color: 229 19 23
      contrast-multiplier: 1.2
      primary-color: 222 74 74
      positive-color: 96 44 68
      negative-color: 359 68 71

    pages:
      # It's not necessary to create a new file for each page and include it, you can simply
      # put its contents here, though multiple pages are easier to manage when separated
      !include: home.yml
  
  home.yml: |
    - name: Home
      # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
      # hide-desktop-navigation: true
      columns:
        - size: small
          widgets:
            - type: calendar
              first-day-of-week: monday

            - type: twitch-channels
              channels:
                - pestily
                - clemovitch
                - usul2000
                - deadlyslob
                - jeanmassiet

            - type: custom-api
              title: Immich stats
              cache: 1d
              url: https://photos.kevingomez.fr/api/server/statistics
              headers:
                x-api-key: ${IMMICH_API_KEY}
                Accept: application/json
              template: |
                <div class="flex justify-between text-center">
                  <div>
                      <div class="color-highlight size-h3">{{ `{{ .JSON.Int "photos" | formatNumber }}` }}</div>
                      <div class="size-h6">PHOTOS</div>
                  </div>
                  <div>
                      <div class="color-highlight size-h3">{{ `{{ .JSON.Int "videos" | formatNumber }}` }}</div>
                      <div class="size-h6">VIDEOS</div>
                  </div>
                  <div>
                      <div class="color-highlight size-h3">{{ `{{ div (.JSON.Int "usage" | toFloat) 1073741824 | toInt | formatNumber }}` }}GB</div>
                      <div class="size-h6">USAGE</div>
                  </div>
                </div>

        - size: full
          widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: Grafana
                  url: https://potatopi.grafana.net/
                  icon: di:grafana
                - title: Immich
                  url: https://photos.kevingomez.fr/
                  icon: di:immich
                - title: LibreTranslate
                  url: https://translate.kevingomez.fr/
                  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/libretranslate.png
                  alt-status-codes: [200, 401]
                - title: RSS
                  url: https://rss.kevingomez.fr/
                  icon: di:miniflux-light
                  alt-status-codes: [200, 401]
                - title: Seafile
                  url: https://files.kevingomez.fr/
                  icon: di:seafile
                - title: Shiori
                  url: https://shiori.kevingomez.fr/
                  icon: di:shiori
                - title: TrueNAS
                  url: https://beet.lab/
                  icon: di:truenas-scale
                  allow-insecure: true

            - type: monitor
              cache: 1m
              title: Media
              sites:
                - title: Jellyfin
                  url: https://tv.kevingomez.fr/
                  icon: di:jellyfin
                  alt-status-codes: [200]
                - title: Prowlarr
                  url: https://prowlarr.kevingomez.fr/
                  icon: di:prowlarr
                  alt-status-codes: [200, 401]
                - title: Radarr
                  url: https://Radarr.kevingomez.fr/
                  icon: di:radarr
                  alt-status-codes: [200, 401]
                - title: Sonarr
                  url: https://sonarr.kevingomez.fr/
                  icon: di:sonarr
                  alt-status-codes: [200, 401]
                - title: Transmission
                  url: https://downloads.kevingomez.fr/
                  icon: di:transmission
                  alt-status-codes: [200, 401]

            - type: group
              widgets:
                - type: reddit
                  subreddit: grafana
                  show-thumbnails: true
                  collapse-after: 8
                - type: reddit
                  subreddit: golang
                  show-thumbnails: true
                  collapse-after: 8
                - type: reddit
                  subreddit: kubernetes
                  show-thumbnails: true
                  collapse-after: 8
                - type: reddit
                  subreddit: programming
                  show-thumbnails: true
                  collapse-after: 8
                - type: reddit
                  subreddit: selfhosted
                  show-thumbnails: true
                  collapse-after: 8
                - type: reddit
                  subreddit: sre
                  show-thumbnails: true
                  collapse-after: 8

        - size: small
          widgets:
            - type: weather
              location: Stockholm, Sweden
              units: metric # alternatively "imperial"
              hour-format: 24h # alternatively "24h"
              # Optionally hide the location from being displayed in the widget
              # hide-location: true

            - type: releases
              cache: 1d
              # Without authentication the Github API allows for up to 60 requests per hour. You can create a
              # read-only token from your Github account settings and use it here to increase the limit.
              # token: ...
              repositories:
                - "0xERR0R/blocky"
                - authelia/authelia
                - glanceapp/glance
                - immich-app/immich
                - jellyfin/jellyfin
                - LibreTranslate/LibreTranslate
                - lldap/lldap
                - miniflux/v2
                - Prowlarr/Prowlarr
                - Radarr/Radarr
                - haiwen/seafile
                - go-shiori/shiori
                - Sonarr/Sonarr
                - traefik/traefik

            - type: server-stats
              servers:
                - type: local
                  name: carrot
