apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: glance

  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance:{{ .Values.image.tag }}
          env:
            - name: TZ
              value: 'Europe/Stockholm'
            - name: IMMICH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich-api-key
                  key: password
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              memory: "25Mi"
              cpu: "10m"

      volumes:
        - name: config-volume
          configMap:
            name: glance-config