apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: glance
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.kevingomez.fr`)
      middlewares:
        - name: forwardauth-authelia
          namespace: authelia
      services:
        - kind: Service
          name: glance-web
          port: 80
  tls:
    certResolver: letsencrypt