apiVersion: 'networking.k8s.io/v1'
kind: 'Ingress'
metadata:
  name: 'glance'
  annotations:
    traefik.ingress.kubernetes.io/router.entryPoints: 'web'
    traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd' # name of your middleware, as defined in your middleware.yml
spec:
  rules:
    - host: 'home.lab'
      http:
        paths:
          - path: '/'
            pathType: 'Prefix'
            backend:
              service:
                name: 'glance-web'
                port:
                  number: 80