apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration

  destination:
    namespace: authelia
    server: {{ .Values.spec.destination.server }}

  sources:
    - chart: authelia
      repoURL: https://charts.authelia.com
      targetRevision: '0.9.17'
      helm:
        valueFiles:
          # Even when the ref field is configured with the path field, $value still represents the root of sources with the ref field.
          - $values/k8s/authelia/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: k8s/authelia
      ref: values