apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration

  destination:
    namespace: crowdsec
    server: {{ .Values.spec.destination.server }}

  sources:
    - chart: crowdsec
      repoURL: https://crowdsecurity.github.io/helm-charts
      targetRevision: '0.19.5'
      helm:
        releaseName: crowdsec
        valueFiles:
          - $values/k8s/crowdsec/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: k8s/crowdsec
      ref: values