apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration

  destination:
    namespace: forgejo-runner
    server: {{ .Values.spec.destination.server }}

  sources:
    - chart: forgejo-runner
      repoURL: oci://codeberg.org/wrenix/helm-charts/forgejo-runner
      targetRevision: "0.6.6"
      helm:
        releaseName: forgejo-runner
        valueFiles:
          - $values/k8s/forgejo-runner/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: k8s/forgejo-runner
      ref: values