apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration

  destination:
    namespace: metallb
    server: {{ .Values.spec.destination.server }}

  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: '0.15.2'
      helm:
        releaseName: metallb
        valueFiles:
          - $values/k8s/metallb/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: k8s/metallb
      ref: values