apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration

  destination:
    namespace: velero
    server: {{ .Values.spec.destination.server }}

  sources:
    - chart: velero
      repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: '11.0.0'
      helm:
        releaseName: velero
        valueFiles:
          - $values/k8s/velero/values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: k8s/velero
      ref: values