apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weather-display-cert
spec:
  secretName: weather-display-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - weather-display.kevingomez.fr
