apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-db
  labels:
    app: umami
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi