blog:
  image: docker.io/kphoen/blog
  image_gemini: docker.io/kphoen/blog-gemini
  tag: "6520bb"
anubis:
  enable: false
  image: ghcr.io/techarohq/anubis
  tag: "main@sha256:657c37d9d213203cc69454c3a199e1e784ba2372023276f2ca79ab22e1d37846"
