{
 "title": "Living room",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "homelab_sensors_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "homelab_sensors_temp", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "homelab_sensors_humidity", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "homelab_sensors_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "homelab_sensors_pressure / 100", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "homelab_sensors_pressure / 100", "legendFormat": "Atmospheric pressure" }
   ]
  }
 ]
}