{
 "title": "Immich",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "component",
    "label": "Component",
    "query": "immich-api,immich-microservices"
   },
   { "name": "logs_filter", "label": "Logs filter" }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{job=\"$component\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "immich_server container logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"immich_server\"}\n|~ \"$logs_filter\""
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "db_client_connection_count{job=\"$component\"}",
     "legendFormat": "{{db_client_connection_state}}"
    },
    {
     "expr": "db_client_connection_pending_requests{job=\"$component\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Database operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(db_client_operation_duration_count{job=\"$component\"}[$__rate_interval])",
     "legendFormat": "{{db_operation_name}}"
    }
   ]
  },
  {
   "title": "Database operations durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(db_client_operation_duration_bucket{job=\"$component\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_count_total{job=\"$component\"}[$__rate_interval])) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP requests durations",
   "type": "heatmap",
   "description": "Duration of inbound HTTP requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_bucket{job=\"$component\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}