{
 "title": "Anubis – blog.kevingomez.fr",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(anubis_challenges_issued{job=~\"integrations/anubis-blog\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Anubis – blog.kevingomez.fr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(anubis_policy_results{instance=~\"$instance\",container=\"anubis\",job=\"integrations/anubis-blog\"}[$__rate_interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Verdicts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (increase(anubis_policy_results{instance=~\"$instance\",container=\"anubis\", job=\"integrations/anubis-blog\"}[$__range]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Challenge results",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(anubis_challenges_validated{instance=~\"$instance\",container=\"anubis\",job=\"integrations/anubis-blog\"}[$__range])",
     "legendFormat": "Validated"
    },
    {
     "expr": "increase(anubis_failed_validations{instance=~\"$instance\",container=\"anubis\",job=\"integrations/anubis-blog\"}[$__range])",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum by(job, instance) (increase(anubis_challenges_issued{job=\"integrations/anubis-blog\",container=\"anubis\",instance=~\"$instance\"}[$__range])) -  increase(anubis_challenges_validated{job=\"integrations/anubis-blog\",instance=~\"$instance\"}[$__range]) - increase(anubis_failed_validations{job=\"integrations/anubis-blog\",instance=~\"$instance\"}[$__range])",
     "legendFormat": "No response"
    }
   ]
  },
  {
   "title": "Allowed requests",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{cluster=~\"homelab\", namespace=\"blog\", container=\"blog\"}"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum (count_over_time({cluster=~\"homelab\", namespace=\"blog\", container=\"blog\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  }
 ]
}