{
 "title": "Miniflux",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Feeds",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(miniflux_feeds{status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max(miniflux_feeds{status=\"enabled\"})",
     "legendFormat": "Enabled"
    },
    { "expr": "max(miniflux_broken_feeds)", "legendFormat": "Broken" },
    {
     "expr": "max(miniflux_feeds{status=\"disabled\"})",
     "legendFormat": "Disabled"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(miniflux_users)", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Entries by Status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(miniflux_entries{status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max(miniflux_entries{status=\"unread\"})",
     "legendFormat": "Unread"
    },
    {
     "expr": "max(miniflux_entries{status=\"read\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "max(miniflux_entries{status=\"removed\"})",
     "legendFormat": "Removed"
    }
   ]
  },
  {
   "title": "Unread",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(miniflux_entries{status=\"unread\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - Memory Used"
    }
   ]
  },
  {
   "title": "Unread entries",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "columns": [
      { "selector": "feed.category.title", "text": "Category", "type": "string" },
      { "selector": "feed.title", "text": "Feed", "type": "string" },
      { "selector": "title", "text": "Title", "type": "string" },
      { "selector": "published_at", "text": "Published", "timestampFormat": "", "type": "timestamp" },
      { "selector": "id", "text": "ID", "type": "string" }
     ],
     "computed_columns": [
      {
       "selector": "feed.title + feed.category.title",
       "text": "",
       "type": "string"
      }
     ],
     "json_options": {
      "columnar": false
     },
     "parser": "simple",
     "root_selector": "entries",
     "source": "url",
     "type": "json",
     "url": "https://rss.kevingomez.fr/v1/entries?status=unread&direction=desc",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Scraper Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(miniflux_scraper_request_duration_bucket[5m])) by (le))",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Background Feed Refresh Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(miniflux_background_feed_refresh_duration_bucket[5m])) by (le))",
     "legendFormat": "Refresh Duration"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"miniflux\"}",
     "legendFormat": "{{instance }} - Open File Descriptors"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Golang Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"miniflux\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"miniflux\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"miniflux\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"miniflux\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - Goroutines"
    },
    {
     "expr": "go_threads{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - OS threads"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"miniflux\"} - go_memstats_frees_total{job=\"miniflux\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - stack_inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - stack_sys"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - heap_alloc"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - heap_sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - heap_idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - heap_inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"miniflux\"}",
     "legendFormat": "{{ instance }} - heap_released"
    }
   ]
  },
  {
   "title": "GC Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"miniflux\"}",
     "legendFormat": "{{instance}}: {{quantile}}"
    }
   ]
  }
 ]
}