apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: davis
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`calendars.kevingomez.fr`)
      services:
        - kind: Service
          name: davis
          port: http
  tls:
    secretName: davis-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: davis-http
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`calendars.kevingomez.fr`)
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - kind: Service
          name: davis
          port: http