apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: davis-db
  labels:
    app: davis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: davis-webdav
  labels:
    app: davis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
