apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-updater
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: ddns-updater

  template:
    metadata:
      labels:
        app: ddns-updater
    spec:
      containers:
        - name: ddns-updater
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            # debug, info, warning or error
            - name: LOG_LEVEL
              value: 'warning'
            - name: TZ
              value: Europe/Stockholm
            - name: PERIOD
              value: '5m'
            # Enable the web server and web UI
            - name: SERVER_ENABLED
              value: 'yes'
            - name: CONFIG
              valueFrom:
                secretKeyRef:
                  name: ddns-updater-config
                  key: password
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              memory: "75Mi"
              cpu: "20m"
