apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-cert
spec:
  secretName: jellyfin-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - tv.kevingomez.fr
