# See https://github.com/jellyfin/jellyfin-helm/blob/master/charts/jellyfin/README.md

image:
  tag: 10.10.7

# Enable hardware acceleration
podSecurityContext:
  supplementalGroups:
    - 44 # "video" group on the host
    - 105 # "render" group on the host

securityContext:
  privileged: true

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
            - key: disktype
              operator: In
              values: [ssd]

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 2Gi
  media:
    enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "0.5"

volumeMounts:
  - mountPath: /library/video
    name: video-library
  - name: hardware-acceleration
    mountPath: /dev/dri

volumes:
  - name: video-library
    nfs:
      server: beet.lab
      path: /mnt/main/Video
  - name: hardware-acceleration
    hostPath:
      path: /dev/dri
