# See https://github.com/jellyfin/jellyfin-helm/blob/master/charts/jellyfin/README.md

# Enable hardware acceleration
podSecurityContext:
  supplementalGroups:
    - 44 # "video" group on the host
    - 105 # "render" group on the host

securityContext:
  privileged: true

nodeSelector:
  'kubernetes.io/hostname': carrot

persistence:
  config:
    enabled: true
    storageClass: local-path
    size: 2Gi
  media:
    enabled: false

volumeMounts:
  - mountPath: /library/video
    name: video-library
  - name: hardware-acceleration
    mountPath: /dev/dri

volumes:
  - name: video-library
    nfs:
      server: beet.lab
      path: /mnt/main/Video
  - name: hardware-acceleration
    hostPath:
      path: /dev/dri
