forgejo:
  image: code.forgejo.org/forgejo/forgejo
  tag: "14.0.4-rootless"

runner:
  image: code.forgejo.org/forgejo/runner
  tag: "12.8.2"

postgres:
  image: postgres
  tag: "17.4-alpine3.21"

anubis:
  enable: true
  image: ghcr.io/techarohq/anubis
  tag: "v1.25.0"
