# https://artifacthub.io/packages/helm/cert-manager/cert-manager

global:
  logLevel: 2 # default: 2

crds:
  enabled: true

prometheus:
  enabled: true

  servicemonitor:
    enabled: true

    endpointAdditionalProperties:
     relabelings:
      - targetLabel: job
        replacement: integrations/cert-manager

# Resources for the cert-manager controller pod.
resources:
  requests:
    cpu: 2m
    memory: 90Mi

webhook:
  resources:
    requests:
      cpu: 2m
      memory: 25Mi

cainjector:
  resources:
    requests:
      cpu: 2m
      memory: 50Mi
