---
- name: Check if mount directory exists
  stat:
    path: "/mnt/k3s-backup"
  register: mount_dir

- name: Ensure k3s backup mountpoint exists
  when: mount_dir.stat.isdir is not defined
  become: true
  ansible.builtin.file:
    path: "/mnt/k3s-backup"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Mount NFS volume
  become: true
  ansible.posix.mount:
    src: "beet.lab:/mnt/main/Backups/k3s"
    path: "/mnt/k3s-backup"
    fstype: nfs
    state: mounted

- name: Create k3s config file
  become: true
  ansible.builtin.copy:
    src: files/k3s-config.yaml
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0644'