---
- name: Check if mount directory exists
  stat:
    path: "/mnt/k3s-backup"
  register: mount_dir

- name: Ensure k3s backup mountpoint exists
  when: mount_dir.stat.isdir is not defined
  become: true
  ansible.builtin.file:
    path: "/mnt/k3s-backup"
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Mount network share
  become: true
  ansible.posix.mount:
    src: "beet.lab:/mnt/main/Backups/k3s"
    path: "/mnt/k3s-backup"
    fstype: nfs
    state: mounted

- name: Create backup script
  become: true
  ansible.builtin.copy:
    src: files/k3s-backup.sh
    dest: /root/k3s-backup.sh
    owner: root
    group: root
    mode: '0700'

- name: Run backup script every night
  become: true
  ansible.builtin.cron:
    name: "k3s backup"
    minute: "0"
    hour: "5"
    job: "/root/k3s-backup.sh"