apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: wallabag

  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: SYMFONY__ENV__MAILER_DSN
              value: smtp://127.0.0.1
            - name: SYMFONY__ENV__FROM_EMAIL
              value: contact@kevingomez.fr
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: https://wallabag.kevingomez.fr
            - name: SYMFONY__ENV__SERVER_NAME
              value: "Your wallabag instance"

            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: pdo_pgsql
            - name: SYMFONY__ENV__DATABASE_HOST
              value: postgres
            - name: SYMFONY__ENV__DATABASE_PORT
              value: '5432'
            - name: SYMFONY__ENV__DATABASE_NAME
              value: wallabag
            - name: SYMFONY__ENV__DATABASE_USER
              value: wallabag
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: SYMFONY__ENV__DATABASE_TABLE_PREFIX
              value: "wallabag_"

            - name: SYMFONY__ENV__REDIS_HOST
              value: redis
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - mountPath: /var/www/wallabag/web/assets/images
              name: wallabag-images
          resources:
            requests:
              memory: "128Mi"
              cpu: "20m"

      volumes:
        - name: wallabag-images
          persistentVolumeClaim:
            claimName: wallabag-images
