# See https://github.com/nextcloud/helm/blob/main/charts/nextcloud/README.md

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: postgres:5432
  database: nextcloud
  user: nextcloud

  existingSecret:
    enabled: true
    secretName: pg-credentials
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: database

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteMany
  size: 50Gi