apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: paperless-ngx

  template:
    metadata:
      labels:
        app: paperless-ngx
    spec:
      #securityContext:
      #  runAsUser: 	3000 # k8s-nfs on nas
      #  runAsGroup: 3001 # k8s-nfs on nas

      containers:
        - name: paperless-ngx
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: PAPERLESS_URL
              value: https://papers.kevingomez.fr
            - name: PAPERLESS_REDIS
              value: redis://redis:6379
            - name: PAPERLESS_DBHOST
              value: postgres
            - name: PAPERLESS_DBNAME
              value: paperless-ngx
            - name: PAPERLESS_DBUSER
              value: postgres
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PAPERLESS_TIKA_ENABLED
              value: '1'
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://gotenberg:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://tika:9998
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Stockholm
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: paperless-ngx-data
            - mountPath: /usr/src/paperless/consume
              name: paperless-ngx-consume
            - mountPath: /usr/src/paperless/media
              name: paperless-ngx-media
            - mountPath: /usr/src/paperless/export
              name: paperless-ngx-export
          #resources:
          #  requests:
          #    memory: "2Gi"
          #    cpu: "0.1"

      volumes:
        - name: paperless-ngx-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-ngx-consume
          persistentVolumeClaim:
            claimName: paperless-consume
        - name: paperless-ngx-media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: paperless-ngx-export
          persistentVolumeClaim:
            claimName: paperless-export