apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libretranslate-models
  labels:
    app: libretranslate
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi