apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-cert
spec:
  secretName: lldap-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - ldap.kevingomez.fr
