apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  labels:
    app: lldap
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi