apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  labels:
    app: lldap
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi