apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  labels:
    app: lldap
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi