apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-cert
spec:
  secretName: immich-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - photos.kevingomez.fr
