apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: immich

  template:
    metadata:
      labels:
        app: immich
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values: [ssd]

      securityContext:
        runAsUser: 	3000 # k8s-nfs on nas
        runAsGroup: 3001 # k8s-nfs on nas

      containers:
        - name: immich
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            # https://immich.app/docs/install/environment-variables
            - name: IMMICH_TELEMETRY_INCLUDE
              value: all
            - name: IMMICH_LOG_LEVEL
              value: log # verbose, debug, log, warn, error
            - name: NO_COLOR
              value: 'true'
            - name: IMMICH_PORT
              value: '2283'

            - name: TZ
              value: Europe/Stockholm

            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: '6379'

            - name: DB_HOSTNAME
              value: postgres
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          ports:
            - name: http
              containerPort: 2283
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-data
          resources:
            requests:
              memory: "800Gi"
              cpu: "0.1"

      volumes:
        - name: immich-data
          nfs:
            server: beet.lab
            path: /mnt/main/k8s/nfs/volumes/pvc-1f25dc05-8b57-43f8-b5ac-ad20609b1d9d
