apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: immich

  template:
    metadata:
      labels:
        app: immich
    spec:
      securityContext:
        runAsUser: 	3000 # k8s-nfs on nas
        runAsGroup: 3001 # k8s-nfs on nas

      containers:
        - name: immich
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            # https://immich.app/docs/install/environment-variables
            - name: IMMICH_TELEMETRY_INCLUDE
              value: all
            - name: IMMICH_LOG_LEVEL
              value: log # verbose, debug, log, warn, error
            - name: NO_COLOR
              value: 'true'

            - name: TZ
              value: Europe/Stockholm

            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: '6379'

            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          ports:
            - name: http
              containerPort: 2283
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-data
          #resources:
          #  requests:
          #    memory: "20Mi"
          #    cpu: "20m"

      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-data
