apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  labels:
    app: immich
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  labels:
    app: postgres
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
