# https://artifacthub.io/packages/helm/ananace-charts/matrix-synapse
# https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse?ref_type=heads

serverName: kevingomez.fr
publicServerName: matrix.kevingomez.fr

ingress:
  tls:
    - secretName: synapse-cert

serviceAccount:
  create: true

synapse:
  resources:
    requests:
      memory: "128Mi"
      cpu: "10m"

postgresql:
  enabled: false

externalPostgresql:
  host: postgres
  port: 5432
  username: synapse

  existingSecret: postgres-password
  existingSecretPasswordKey: password

  database: synapse

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteMany
  size: 10Gi
