apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  # https://doc.traefik.io/traefik/reference/routing-configuration/http/middlewares/headers/
  headers:
    # Enable HTTP Strict Transport Security (HSTS)
    stsSeconds: 31536000
    stsPreload: true

    # X-Content-Type-Options header
    contentTypeNosniff: true

    # Prevent browser from running any kind of active content inside the page
    frameDeny: true # Adds the header X-Frame-Options with the value DENY

    # X-XSS-Protection header to enable browser-based cross-site scripting protection
    browserXssFilter: true # Adds the header X-XSS-Protection with the value `1; mode=block`

    # Referrer Policy to limit the amount of information the browser sends as referrer
    referrerPolicy: "no-referrer-when-downgrade"