ingressClass:
  name: traefik
  isDefaultClass: true

deployment:
  podAnnotations:
    k8s.grafana.com/scrape: 'true'
    k8s.grafana.com/metrics.portNumber: '9100'
    k8s.grafana.com/metrics.scrapeInterval: '30s'

providers:
  kubernetesCRD:
    ingressClass: traefik
    allowCrossNamespace: true
  kubernetesIngress:
    ingressClass: traefik

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ['websecure']
    matchRule: "Host(`traefik.home.lab`)"
    middlewares:
      - name: forwardauth-authelia
        namespace: authelia

logs:
  general:
    level: "WARN" # TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC. Default is: "INFO"

globalArguments: [] # To disable new version checks and anonymous usage reports
