ingressClass:
  name: traefik
  isDefaultClass: true

deployment:
  replicas: 3 # hopefully one per node, but it should be fine if not.
  revisionHistoryLimit: 3
  podAnnotations:
    k8s.grafana.com/scrape: "true"
    k8s.grafana.com/metrics.portNumber: "9100"
    k8s.grafana.com/metrics.scrapeInterval: "30s"
    k8s.grafana.com/job: "integrations/traefik"

providers:
  kubernetesCRD:
    ingressClass: traefik
    allowCrossNamespace: true
  kubernetesIngress:
    ingressClass: traefik

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    matchRule: "Host(`traefik.kevingomez.fr`)"
    middlewares:
      - name: forwardauth-authelia
        namespace: authelia
    tls:
      secretName: traefik-cert

logs:
  general:
    level: "WARN" # TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and PANIC. Default is: "INFO"

  access:
    enabled: true

globalArguments: [] # To disable new version checks and anonymous usage reports

resources:
  requests:
    memory: "128Mi"
    cpu: "0.02"

persistence:
  enabled: false

service:
  spec:
    externalTrafficPolicy: Local

ports:
  web:
    expose:
      default: true

  websecure:
    transport:
      respondingTimeouts:
        # https://github.com/immich-app/immich/discussions/8872
        readTimeout: "0s"

    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "10.43.0.0/16"
        - "10.10.20.0/24" # local
    proxyProtocol:
      trustedIPs:
        - "10.42.0.0/16"
        - "10.43.0.0/16"
        - "10.10.20.0/24" # local
