apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiori
spec:
  replicas: 1
  revisionHistoryLimit: 3

  # the PVC used by prowlarr is defined as ReadWriteOnce, so only one pod can
  # access it at any time
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: shiori

  template:
    metadata:
      labels:
        app: shiori
    spec:
      automountServiceAccountToken: false

      containers:
        - name: shiori
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["/usr/bin/shiori", "serve"]
          imagePullPolicy: Always
          env:
            - name: SHIORI_DIR
              value: /srv/shiori
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /srv/shiori
              name: shiori-data
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"

      volumes:
        - name: shiori-data
          persistentVolumeClaim:
            claimName: shiori-data
        - name: tmp
          emptyDir:
            medium: Memory
