apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data
  labels:
    app: shiori
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi