apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  labels:
    app: radarr
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi