---
- name: Install alloy
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
    apply:
      become: true
  vars:
    alloy_config: "{{ lookup('ansible.builtin.template', './files/config.alloy.j2') }}"

- name: Setup tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ vault_tailscale_authkey }}"
    tailscale_tags: ["homelab"]
    tailscale_args: "--ssh --advertise-exit-node"
    tailscale_oauth_ephemeral: false

- name: Setup firewall
  ansible.builtin.include_tasks: ./ufw.yml

- name: Install required packages
  become: true
  ansible.builtin.apt:
    pkg:
      - nfs-common
      - firmware-linux-nonfree
    update_cache: true