apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  labels:
    app: transmission
spec:
  storageClassName: truenas-nfs-api-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi