blocky__version: v0.25
blocky__arch: "{{ ansible_machine }}"
blocky__base: "blocky-{{ blocky__version }}"
blocky__system: "{{ ansible_system }}"
blocky__base_url: https://github.com/0xERR0R/blocky/releases/download
blocky__download_url: "{{ blocky__base_url }}/{{ blocky__version }}/blocky_{{ blocky__version }}_{{ blocky__system }}_{{ blocky__arch }}.tar.gz"
blocky__checksum_url: "{{ blocky__base_url }}/{{ blocky__version }}/blocky_checksums.txt"
blocky__download_path: /tmp
blocky__install_path: /opt/blocky
blocky__readiness_check_enabled: true

keepalived_exporter__version: 1.7.0
keepalived_exporter__base: "keepalived-exporter-{{ keepalived_exporter__version }}"
keepalived_exporter__system: "{{ ansible_system }}"
keepalived_exporter__arch: "{{ ansible_machine }}"
keepalived_exporter__download_url: "https://github.com/mehdy/keepalived-exporter/releases/download/v{{ keepalived_exporter__version }}/keepalived-exporter_{{ keepalived_exporter__version }}_{{ keepalived_exporter__system }}_{{ keepalived_exporter__arch }}.tar.gz"
keepalived_exporter__install_path: /opt/keepalived-exporter
keepalived_exporter__download_path: /opt/keepalived-exporter

keepalived__vip: '10.10.10.211'

# arbitrary unique number from 1 to 255
# used to differentiate multiple instances of vrrpd
keepalived__virtual_router_id: 42

# for electing MASTER, highest priority wins.
# The valid range of values for priority is [1-255], with priority
# 255 meaning "address owner".
# To be MASTER, it is recommended to make this 50 more than on
# other machines.
keepalived__vrrp_priority: 100