---
- name: Setup tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ vault_tailscale_authkey }}"
    tailscale_tags: ["homelab"]
    tailscale_args: "--ssh --advertise-exit-node --advertise-routes=10.10.10.0/24"
    tailscale_oauth_ephemeral: false

- name: Ensure IP forwarding is enabled
  become: true
  ansible.builtin.copy:
    src: files/99-tailscale.conf
    dest: /etc/sysctl.d/99-tailscale.conf
    owner: root
    group: root
    mode: '0644'

- name: Load 99-tailscale.conf
  become: true
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf