---
- name: Setup tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ vault_tailscale_authkey }}"
    tailscale_tags: ["homelab"]
    tailscale_args: "--ssh --advertise-exit-node --advertise-routes=10.10.10.0/24"
    tailscale_oauth_ephemeral: false
