apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
spec:
  secretName: gitea-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - git.kevingomez.fr
