apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: "Recreate"

  selector:
    matchLabels:
      app: gitea

  template:
    metadata:
      labels:
        app: gitea
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values: [ssd]

      terminationGracePeriodSeconds: 30

      containers:
        - name: gitea
          image: docker.gitea.com/gitea:{{ .Values.gitea.tag }}
          env:
            # Misc
            - name: GITEA_TEMP
              value: /tmp/gitea

            # Metrics - https://docs.gitea.com/administration/config-cheat-sheet#metrics-metrics
            - name: GITEA__metrics__ENABLED
              value: 'true'
            - name: GITEA__metrics__ENABLED_ISSUE_BY_LABEL
              value: 'true'
            - name: GITEA__metrics__ENABLED_ISSUE_BY_REPOSITORY
              value: 'true'
            - name: GITEA__metrics__TOKEN
              valueFrom:
                secretKeyRef:
                  name: metrics-token
                  key: password

            # Database
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: postgres:5432
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: gitea
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password

            # Mailer
            - name: GITEA__mailer__ENABLED
              value: "true"
            - name: GITEA__mailer__FROM
              value: noreply@git.kevingomez.fr
            - name: GITEA__mailer__PROTOCOL
              value: "smtp+starttls"
            - name: GITEA__mailer__SMTP_ADDR
              value: smtp.fastmail.com
            - name: GITEA__mailer__SMTP_PORT
              value: "587"
            - name: GITEA__mailer__USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: GITEA__mailer__PASSWD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
          resources:
            requests:
              memory: "264Mi"
              cpu: "20m"

          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 2222

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10

          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: gitea-data
              mountPath: /var/lib/gitea
            - name: gitea-config
              mountPath: /etc/gitea
            - name: temp
              mountPath: /tmp

      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: gitea-config
          persistentVolumeClaim:
            claimName: gitea-config
        - name: temp
          emptyDir: {}