apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: gitea

  template:
    metadata:
      labels:
        app: gitea
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values: [ssd]

      containers:
        - name: gitea
          image: docker.gitea.com/gitea:{{ .Values.gitea.tag }}
          env:
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: postgres:5432
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: gitea
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password

          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 2222

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          volumeMounts:
            - name: gitea-data
              mountPath: /var/lib/gitea

      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data