apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`git.kevingomez.fr`)
      services:
        - kind: Service
          name: gitea-web
          port: http
  tls:
    certResolver: letsencrypt