apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitea
spec:
  selector:
    matchLabels:
      app: gitea

  namespaceSelector:
    matchNames:
      - gitea

  jobLabel: integrations/gitea
  endpoints:
    - port: http
      interval: 30s
      scheme: http
      scrapeTimeout: 5s
      authorization:
        type: Bearer
        credentials:
          name: metrics-token
          key: password
          optional: false