---
- name: Install keepalived
  become: true
  block:
    - name: Install keepalived
      ansible.builtin.include_role:
        name: ansible-keepalived
      vars:
        keepalived_global_defs:
          # Don't run scripts configured to be run as root if any part of the path
          # is writable by a non-root user.
          - enable_script_security

        keepalived_scripts:
          blocky_responding:
            check_script: "/usr/bin/dig google.fr @127.0.0.1"
            timeout:  2 # # seconds after which script is considered to have failed
            interval: 3 # seconds between script invocations
            rise:     5 # required number of successes for OK transition
            fall:     2 # required number of successes for KO transition
            user:     blocky blocky # user/group names to run script under

        keepalived_instances:
          blocky:
            interface: "{{ ansible_default_ipv4.interface }}"
            state: "BACKUP"
            virtual_router_id: "{{ keepalived__virtual_router_id }}"
            priority: "{{ keepalived__vrrp_priority }}"
            vips:
              - "{{ keepalived__vip }} dev {{ ansible_default_ipv4.interface }}"
            track_scripts:
              - blocky_responding
