---
- name: Install keepalived
  become: true
  ansible.builtin.apt:
    pkg:
      - keepalived
    update_cache: true
  notify: Restart keepalived

- name: Configure keepalived
  become: true
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Ensure keepalived-exporter install and conf dirs exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  with_items:
    - "{{ keepalived_exporter__install_path }}/{{ keepalived_exporter__base }}"

- name: Check if keepalived-exporter has been installed already
  become: true
  ansible.builtin.stat:
    path: "{{ keepalived_exporter__install_path }}/{{ keepalived_exporter__base }}/keepalived-exporter"
  register: install_status

- name: Download keepalived-exporter archive
  become: true
  ansible.builtin.get_url:
    url: "{{ keepalived_exporter__download_url }}"
    dest: "{{ keepalived_exporter__download_path }}/{{ keepalived_exporter__base }}.tgz"
    mode: "0644"
    force: false
  when: not install_status.stat.exists
  register: download_status

- name: Expand keepalived-exporter archive
  become: true
  ansible.builtin.unarchive:
    src: "{{ keepalived_exporter__download_path }}/{{ keepalived_exporter__base }}.tgz"
    dest: "{{ keepalived_exporter__install_path }}/{{ keepalived_exporter__base }}/"
    mode: "0755"
    copy: false
  when: download_status.changed or not install_status.stat.exists

- name: Create link to keepalived-exporter
  become: true
  ansible.builtin.file:
    src: "{{ keepalived_exporter__install_path }}/{{ keepalived_exporter__base }}/keepalived-exporter"
    dest: "{{ keepalived_exporter__install_path }}/keepalived-exporter"
    mode: "0755"
    state: link
  notify: Restart keepalived-exporter

- name: Configure keepalived-exporter service
  become: true
  ansible.builtin.template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart keepalived-exporter

- name: Ensure keepalived-exporter service is enabled and running
  become: true
  ansible.builtin.systemd:
    name: keepalived-exporter
    state: started
    daemon_reload: true
    enabled: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers