apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: blog

  template:
    metadata:
      annotations:
        k8s.grafana.com/scrape: 'true'
        k8s.grafana.com/metrics.portNumber: '9090'
        k8s.grafana.com/metrics.scrapeInterval: '30s'
        k8s.grafana.com/job: 'integrations/anubis-blog'
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: {{ .Values.blog.image }}:{{ .Values.blog.tag }}
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: 5m

        - name: anubis
          image: {{ .Values.anubis.image }}:{{ .Values.anubis.tag }}
          ports:
            - name: anubis
              containerPort: 8080
          env:
            - name: "BIND"
              value: ":8080"
            - name: "DIFFICULTY"
              value: "4"
            - name: ED25519_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: anubis-private-key
                  key: password
            - name: "METRICS_BIND"
              value: ":9090"
            - name: "SERVE_ROBOTS_TXT"
              value: "false"
            - name: "TARGET"
              value: "http://localhost:80"
            - name: "OG_PASSTHROUGH"
              value: "true"
            - name: "OG_EXPIRY_TIME"
              value: "24h"
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault