apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: anubis
  selector:
    app: blog