apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.anubis.enable }}
    - protocol: TCP
      port: 8080
      targetPort: anubis
      name: anubis
    {{ end }}
  selector:
    app: blog
---
apiVersion: v1
kind: Service
metadata:
  name: blog-gemini
  labels:
    app: blog-gemini
spec:
  type: ClusterIP
  ports:
    - port: 1965
      targetPort: gemini
      protocol: TCP
      name: gemini
  selector:
    app: blog-gemini
