apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-controller
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - metallb
  podMetricsEndpoints:
    - path: /metrics
      port: monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/name: metallb
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metallb-speaker
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - metallb
  podMetricsEndpoints:
    - path: /metrics
      port: monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: speaker
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/name: metallb
