# https://github.com/metallb/metallb/blob/942c2fe54a75ac6353d3099eeebff33b6b8fe3f0/charts/metallb/values.yaml

controller:
  logLevel: warn
  resources:
    requests:
      memory: "64Mi"
      cpu: 3m

speaker:
  logLevel: warn
  resources:
    requests:
      memory: "110Mi"
      cpu: 3m
