apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-cert
spec:
  secretName: sonarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sonarr.kevingomez.fr
