apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: sonarr

  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          env:
            - name: TZ
              value: 'Europe/Stockholm'
            - name: PUID
              value: '1000'
            - name: PGID
              value: '3000'
          ports:
            - name: http
              containerPort: 8989
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: series-library
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              memory: "512Mi"
              cpu: "20m"

      volumes:
        - name: sonarr-config
          nfs:
            server: beet.lab
            path: /mnt/main/k8s/nfs/volumes/pvc-009ef461-68ad-4ea6-b94c-69ab3584e44e
        - name: series-library
          nfs:
            server: beet.lab
            path: /mnt/main/Video/Series
        - name: downloads
          nfs:
            server: beet.lab
            path: /mnt/main/Downloads