apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: unpoller
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - unpoller
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: unpoller
