name: Publish Grafana manifests
on:
  push:
    branches: [main]

jobs:
  publish-grafana-manifests:
    name: Publish Grafana manifests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup grafanactl
        uses: ./.github/actions/setup-grafanactl

      - name: Push resources
        run: |
          grafanactl config set contexts.default.grafana.server "${{ secrets.GRAFANA_SERVER }}"
          grafanactl config set contexts.default.grafana.stack-id "${{ secrets.GRAFANA_STACK_ID }}"
          grafanactl config set contexts.default.grafana.token "${{ secrets.GRAFANA_TOKEN }}"

          grafanactl resources push -p ./grafana -v